export const REGISTER_SUCCESS = 'REGISTER_SUCCESS' ;
export const REGISTER_FAIL = 'REGISTER_FAIL' ;
export const USER_LOADED = 'USER_LOADED' ;
export const AUTH_ERROR = 'AUTH_ERROR' ;
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS' ;
export const LOGIN_FAIL = 'LOGIN_FAIL' ;
export const COMPLAINTPOST_SUCCESS='POST_SUCCESS';
export const COMPLAINTPOST_FAILURE='POST_FAILURE';
